### PR TITLE
Upgrade Hugo to 0.69.0 version

### LINKED ISSUE #28: Upgrade Hugo to 0.69.0 version

### PR DESCRIPTION
**Pull request by Jean85**
Fixes #28

### CODE REVIEW

**Comment by Jean85** [comment]
I've found just two small issues:

Categories are no longer capitalized:

immagine

VS

immagine

ToC losts one level:

immagine

VS

immagine

**Comment by salvatorecordiano** [comment]
@Jean85, Issues solved. You should also update hugo-future-imperfect theme to see this changes

**Comment by Jean85** [comment]
@salvatorecordiano you can do it yourself, just enter the folder, do a git pull, then go back to the root and do a git commit and push to save the updates

**Comment by salvatorecordiano** [comment]
Done @Jean85, thank you

**Comment by Jean85** [comment]
ToC is fine now :+1: categories are still all lowercase :disappointed:

**Comment by salvatorecordiano** [comment]
Ok @Jean85, I think something went wrong because of my inexperience with submodules.

Now I checked all on a new git folder with the following steps:
```
git checkout 2004_issue28_update_hugo
git submodule update
```

The submodule is now referring to the right commit.
```
git submodule
f39fa75bb9f7ba50dc44b7bf266902aa3847b4e2 themes/hugo-future-imperfect (v0.3-119-gf39fa75)
```

If it is ok, please merge and deploy it. Thanks

**Comment by Jean85** [comment]
I'm fixing the categories page further following the docs: https://gohugo.io/templates/taxonomy-templates/#order-alphabetically-example

There's an upgrade step possible from Hugo 0.55+

**Comment by Jean85** [comment]
Done. I've pushed [a new commit](https://github.com/facile-it/hugo-future-imperfect/commit/ba98d0ef985e87f36ea77a5bb0ec1e9030e65c28) to our forked theme, imported it here and fixed the submodule.

**Pull request merged**
